apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zero2prod
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: europe-west3-docker.pkg.dev/zero2prod-473829/zero2prod/zero2prod:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENVIRONMENT
              value: "prod"
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
