name: Audit
on:
  schedule:
    - cron: "0 2 1 * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-deny
      - name: Vulnerabilities
        run: cargo deny check advisories
