name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: zero2prod-473829
  SERVICE_NAME: zero2prod-app
  REGION: europe-west3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # GCP_SA_KEY is a secret set up in the github repository secrets

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and Push
        run: |
          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/zero2prod/zero2prod:${{ github.sha }} .
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/zero2prod/zero2prod:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/zero2prod/zero2prod:${{ github.sha }}
          env_vars: |
            APP_DATABASE__URI=${{ secrets.APP_DATABASE__URI }}
